#!/bin/bash

echo "🔥 Firebase Firestore Rules 배포 스크립트"
echo "========================================"
echo ""
echo "이 스크립트는 Firestore 보안 규칙을 배포합니다."
echo ""
echo "📋 필요한 작업:"
echo ""
echo "1. 터미널에서 다음 명령어 실행:"
echo "   firebase login"
echo ""
echo "2. 브라우저에서 Google 계정으로 로그인"
echo ""
echo "3. 로그인 완료 후 다음 명령어 실행:"
echo "   firebase use innerspell-an7ce"
echo ""
echo "4. 마지막으로 Rules 배포:"
echo "   firebase deploy --only firestore:rules"
echo ""
echo "또는 Firebase Console에서 직접 수정:"
echo "1. https://console.firebase.google.com 접속"
echo "2. innerspell-an7ce 프로젝트 선택"
echo "3. Firestore Database → Rules 탭"
echo "4. firestore.rules 파일 내용 복사하여 붙여넣기"
echo "5. Publish 버튼 클릭"
echo ""
echo "✅ 수정된 규칙이 추가되었습니다:"
echo "   - userReadings 컬렉션 읽기/쓰기 권한"